"""add redirects table

Revision ID: 79f0c394539e
Revises: 7aee5deff428
Create Date: 2026-07-10 13:53:12.415567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f0c394539e'
down_revision: Union[str, Sequence[str], None] = '7aee5deff428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('destination_url', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=True),
    sa.Column('redirect_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_id'), 'redirects', ['id'], unique=False)
    op.create_index(op.f('ix_redirects_slug'), 'redirects', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirects_slug'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_id'), table_name='redirects')
    op.drop_table('redirects')
    # ### end Alembic commands ###
